version: 2

project_name: meta

before:
  hooks:
    - go mod tidy

builds:
  - id: meta
    main: ./cmd/meta
    binary: meta
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: meta
    builds:
      - meta
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  use: git
